//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitySheets
    {
        public int ActivitySheetID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string TaskModule { get; set; }
        public string Description { get; set; }
        public string Dependencies { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
