//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approvals
    {
        public int ApprovalID { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> OverallStatus { get; set; }
        public Nullable<int> L1ApprovalStatus { get; set; }
        public Nullable<int> L1ApprovalStaffID { get; set; }
        public Nullable<System.DateTime> L1ApproveDateTime { get; set; }
        public string L1Notes { get; set; }
        public Nullable<int> L2ApprovalStatus { get; set; }
        public Nullable<int> L2ApprovalStaffID { get; set; }
        public Nullable<System.DateTime> L2ApproveDateTime { get; set; }
        public string L2Notes { get; set; }
    }
}
