//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCards
    {
        public int BankCardID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> CardType { get; set; }
        public string Bank { get; set; }
        public string CardNo { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> DocumentID { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
