//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIQuestionGroupLink
    {
        public int KPIQuestionGroupLinkID { get; set; }
        public int KPIQuestionGroupID { get; set; }
        public int KPIQuestionID { get; set; }
        public int Rank { get; set; }
    
        public virtual KPIQuestion KPIQuestion { get; set; }
        public virtual KPIQuestionGroup KPIQuestionGroup { get; set; }
    }
}
