//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveBlockDates
    {
        public int LeaveBlockDateID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BlockType { get; set; }
        public Nullable<int> LinkType { get; set; }
        public Nullable<int> LinkID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Reason { get; set; }
        public Nullable<int> StaffID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
    }
}
