//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int LeaveID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<bool> Emergency { get; set; }
        public Nullable<bool> HalfDay { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
