//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merit
    {
        public int MeritID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> NominationStaffID { get; set; }
        public Nullable<int> MeritTypeID { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> ActivePeriodDays { get; set; }
        public Nullable<decimal> TimeSpent { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> MeritPoints { get; set; }
    
        public virtual MeritType MeritType { get; set; }
    }
}
