//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OvertimeTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OvertimeTypes()
        {
            this.OverTime = new HashSet<OverTime>();
        }
    
        public int OvertimeTypeID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string OvertimeDesc { get; set; }
        public Nullable<decimal> OTRate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OverTime> OverTime { get; set; }
    }
}
