//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionDuties
    {
        public int PositionDutyID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> DutyID { get; set; }
        public Nullable<int> CreateDate { get; set; }
    
        public virtual Duties Duties { get; set; }
        public virtual Position Position { get; set; }
    }
}
