//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDocumentation
    {
        public int ProductDocumentationID { get; set; }
        public int ProductVersionID { get; set; }
        public int ReleaseDate { get; set; }
        public string Link { get; set; }
        public byte[] Doc { get; set; }
    
        public virtual ProductVersions ProductVersions { get; set; }
    }
}
