//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillsetGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SkillsetGroups()
        {
            this.SkillSet = new HashSet<SkillSet>();
        }
    
        public int SkillsetGroupID { get; set; }
        public int CompanyID { get; set; }
        public string GroupDesc { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> MeasureType { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillSet> SkillSet { get; set; }
    }
}
