//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffEmpEvents
    {
        public int StaffEmpEventsID { get; set; }
        public int StaffID { get; set; }
        public int Status { get; set; }
        public System.DateTime StatusDate { get; set; }
        public Nullable<int> NextStatus { get; set; }
        public Nullable<System.DateTime> NextStatusDate { get; set; }
        public string Notes { get; set; }
    }
}
