//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportDocumentation
    {
        public int SupportDocumentationID { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> DocumentID { get; set; }
    }
}
