//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMembers
    {
        public int TeamMemberID { get; set; }
        public int TeamID { get; set; }
        public int StaffID { get; set; }
        public Nullable<bool> Teamleader { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
