//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claims
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claims()
        {
            this.TravelLog = new HashSet<TravelLog>();
        }
    
        public int ClaimID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> TravelLogID { get; set; }
        public Nullable<System.DateTime> ClaimDate { get; set; }
        public Nullable<int> ClaimType { get; set; }
        public Nullable<bool> CashClaim { get; set; }
        public Nullable<int> BankCardID { get; set; }
        public string Description { get; set; }
        public Nullable<int> StartingOdo { get; set; }
        public Nullable<int> Km { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelLog> TravelLog { get; set; }
    }
}
