//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanyPolicies = new HashSet<CompanyPolicies>();
            this.Department = new HashSet<Department>();
            this.Documents = new HashSet<Documents>();
            this.Duties = new HashSet<Duties>();
            this.EmploymentType = new HashSet<EmploymentType>();
            this.KPIInstance = new HashSet<KPIInstance>();
            this.KPIQuestionGroup = new HashSet<KPIQuestionGroup>();
            this.LeaveBlockDates = new HashSet<LeaveBlockDates>();
            this.LeaveBlockDates1 = new HashSet<LeaveBlockDates>();
            this.LeaveType = new HashSet<LeaveType>();
            this.LeaveType1 = new HashSet<LeaveType>();
            this.OvertimeTypes = new HashSet<OvertimeTypes>();
            this.OvertimeTypes1 = new HashSet<OvertimeTypes>();
            this.Position = new HashSet<Position>();
            this.SecurityRoles = new HashSet<SecurityRoles>();
            this.SkillsetGroups = new HashSet<SkillsetGroups>();
            this.Teams = new HashSet<Teams>();
        }
    
        public int CompanyID { get; set; }
        public System.Guid CompanyGUID { get; set; }
        public Nullable<int> CompanyGroupID { get; set; }
        public string CountryISO { get; set; }
        public string DefaultCurrencyISO { get; set; }
        public string CompanyName { get; set; }
        public string PhysicalAddress1 { get; set; }
        public string PhysicalAddress2 { get; set; }
        public string PhysicalAddress3 { get; set; }
        public string PhysicalAddress4 { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddress3 { get; set; }
        public string BillingAddress4 { get; set; }
        public Nullable<decimal> TravelRefundPerKm { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<int> OvertimePolicyID { get; set; }
        public Nullable<int> ClaimsPolicyID { get; set; }
        public Nullable<int> TravelPolicyID { get; set; }
        public Nullable<int> MobileDevPolicyID { get; set; }
        public Nullable<int> BankcardPolicyID { get; set; }
        public Nullable<int> EquipmentPolicyID { get; set; }
        public bool PubHolidayMonIfSunRule { get; set; }
    
        public virtual CompanyGroup CompanyGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyPolicies> CompanyPolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duties> Duties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmploymentType> EmploymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPIInstance> KPIInstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPIQuestionGroup> KPIQuestionGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveBlockDates> LeaveBlockDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveBlockDates> LeaveBlockDates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveType> LeaveType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveType> LeaveType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OvertimeTypes> OvertimeTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OvertimeTypes> OvertimeTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityRoles> SecurityRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillsetGroups> SkillsetGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teams> Teams { get; set; }
    }
}
