//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Duties()
        {
            this.PositionDuties = new HashSet<PositionDuties>();
        }
    
        public int DutyID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> DutyGroupID { get; set; }
        public string DutyName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> TreeLevel { get; set; }
        public Nullable<bool> Suggestion { get; set; }
        public Nullable<int> SuggestionStaffID { get; set; }
        public Nullable<int> KPIQuestionGroupID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual KPIQuestionGroup KPIQuestionGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PositionDuties> PositionDuties { get; set; }
    }
}
