//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupSkillset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupSkillset()
        {
            this.SkillSet = new HashSet<SkillSet>();
        }
    
        public int GroupSkillsetID { get; set; }
        public int SkillsetGroupID { get; set; }
        public string Skill { get; set; }
        public string SkillDesc { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual GroupSkillsetGroups GroupSkillsetGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillSet> SkillSet { get; set; }
    }
}
