//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HrTrackEntities : DbContext
    {
        public HrTrackEntities()
            : base("name=HrTrackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityAssignees> ActivityAssignees { get; set; }
        public virtual DbSet<ActivitySheets> ActivitySheets { get; set; }
        public virtual DbSet<Approvals> Approvals { get; set; }
        public virtual DbSet<BankCards> BankCards { get; set; }
        public virtual DbSet<Claims> Claims { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyGroup> CompanyGroup { get; set; }
        public virtual DbSet<CompanyPolicies> CompanyPolicies { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Duties> Duties { get; set; }
        public virtual DbSet<EmploymentType> EmploymentType { get; set; }
        public virtual DbSet<GroupPolicies> GroupPolicies { get; set; }
        public virtual DbSet<GroupSkillset> GroupSkillset { get; set; }
        public virtual DbSet<GroupSkillsetGroups> GroupSkillsetGroups { get; set; }
        public virtual DbSet<KPIIncident> KPIIncident { get; set; }
        public virtual DbSet<KPIInstance> KPIInstance { get; set; }
        public virtual DbSet<KPILinks> KPILinks { get; set; }
        public virtual DbSet<KPIQuestion> KPIQuestion { get; set; }
        public virtual DbSet<KPIQuestionGroup> KPIQuestionGroup { get; set; }
        public virtual DbSet<KPIQuestionGroupLink> KPIQuestionGroupLink { get; set; }
        public virtual DbSet<KPIQuestionnaire> KPIQuestionnaire { get; set; }
        public virtual DbSet<KPIRater> KPIRater { get; set; }
        public virtual DbSet<KPIRating> KPIRating { get; set; }
        public virtual DbSet<Leave> Leave { get; set; }
        public virtual DbSet<LeaveBlockDates> LeaveBlockDates { get; set; }
        public virtual DbSet<LeaveType> LeaveType { get; set; }
        public virtual DbSet<Licences> Licences { get; set; }
        public virtual DbSet<LicenceTypes> LicenceTypes { get; set; }
        public virtual DbSet<Merit> Merit { get; set; }
        public virtual DbSet<MeritType> MeritType { get; set; }
        public virtual DbSet<MobileDevices> MobileDevices { get; set; }
        public virtual DbSet<OverTime> OverTime { get; set; }
        public virtual DbSet<OvertimeTypes> OvertimeTypes { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<PositionApprovers> PositionApprovers { get; set; }
        public virtual DbSet<PositionDuties> PositionDuties { get; set; }
        public virtual DbSet<ProductDocumentation> ProductDocumentation { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductVersions> ProductVersions { get; set; }
        public virtual DbSet<SecurityRoles> SecurityRoles { get; set; }
        public virtual DbSet<SerialLicence> SerialLicence { get; set; }
        public virtual DbSet<SkillSet> SkillSet { get; set; }
        public virtual DbSet<SkillsetGroups> SkillsetGroups { get; set; }
        public virtual DbSet<SkillsMatrix> SkillsMatrix { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StaffEmpEvents> StaffEmpEvents { get; set; }
        public virtual DbSet<StaffLanguage> StaffLanguage { get; set; }
        public virtual DbSet<StaffPositionHist> StaffPositionHist { get; set; }
        public virtual DbSet<StaffRemunirationHist> StaffRemunirationHist { get; set; }
        public virtual DbSet<SupportDocumentation> SupportDocumentation { get; set; }
        public virtual DbSet<SupportRoles> SupportRoles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemNotice> SystemNotice { get; set; }
        public virtual DbSet<TeamMembers> TeamMembers { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<TravelLog> TravelLog { get; set; }
        public virtual DbSet<Vehichles> Vehichles { get; set; }
        public virtual DbSet<Visas> Visas { get; set; }
    }
}
