//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPILinks
    {
        public int KPILinkID { get; set; }
        public int ItemType { get; set; }
        public int ItemID { get; set; }
        public int KPIQuestionGroup { get; set; }
    
        public virtual KPIQuestionGroup KPIQuestionGroup1 { get; set; }
    }
}
