//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIQuestionGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KPIQuestionGroup()
        {
            this.Duties = new HashSet<Duties>();
            this.KPILinks = new HashSet<KPILinks>();
            this.KPIQuestionGroupLink = new HashSet<KPIQuestionGroupLink>();
            this.KPIQuestionnaire = new HashSet<KPIQuestionnaire>();
        }
    
        public int KPIQuestionGroupID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Rank { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duties> Duties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPILinks> KPILinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPIQuestionGroupLink> KPIQuestionGroupLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KPIQuestionnaire> KPIQuestionnaire { get; set; }
    }
}
