//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIRater
    {
        public int KPIRaterID { get; set; }
        public Nullable<int> KPIInstanceID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> RaterID { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
