//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licences
    {
        public int LicenceID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> LicenceTypeID { get; set; }
        public string CountryISO { get; set; }
        public string ProvinceState { get; set; }
        public string LicNo { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> DocumentID { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual LicenceTypes LicenceTypes { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
