//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeritType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeritType()
        {
            this.Merit = new HashSet<Merit>();
        }
    
        public int MeritTypeID { get; set; }
        public string Name { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<bool> Demerit { get; set; }
        public Nullable<int> ActiveDays { get; set; }
        public Nullable<int> DefaultPoints { get; set; }
        public Nullable<int> CompanyPoliciesID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Merit> Merit { get; set; }
    }
}
