//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileDevices
    {
        public int MobileDevicesID { get; set; }
        public Nullable<int> Type { get; set; }
        public string CountryISO { get; set; }
        public string PUK { get; set; }
        public string PIN { get; set; }
        public string PhoneNumber { get; set; }
        public string ContractCompany { get; set; }
        public Nullable<System.DateTime> ContractExp { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string Description { get; set; }
        public Nullable<int> DocumentID { get; set; }
    
        public virtual Documents Documents { get; set; }
    }
}
