//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverTime
    {
        public int OverTimeID { get; set; }
        public int OvertimeTypeID { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual OvertimeTypes OvertimeTypes { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
