//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position()
        {
            this.PositionApprovers = new HashSet<PositionApprovers>();
            this.PositionDuties = new HashSet<PositionDuties>();
        }
    
        public int PositionID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public bool Director { get; set; }
        public Nullable<int> PositionColour { get; set; }
        public int DepartmentID { get; set; }
        public int SecurityRoleID { get; set; }
        public Nullable<int> CurrentStaffID { get; set; }
        public string PositionName { get; set; }
        public string PositionDescription { get; set; }
        public System.DateTime PositionDate { get; set; }
        public bool Redundant { get; set; }
        public Nullable<System.DateTime> RedundantDate { get; set; }
        public string RedundantReason { get; set; }
        public Nullable<int> ReportsToPrimaryPos { get; set; }
        public Nullable<int> ReportsToSecondaryPos { get; set; }
        public Nullable<int> KPIQuestionGroupID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PositionApprovers> PositionApprovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PositionDuties> PositionDuties { get; set; }
    }
}
