//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityRoles
    {
        public int SecurityRoleID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string RoleDescription { get; set; }
        public Nullable<bool> GroupAdministrator { get; set; }
        public Nullable<bool> Administrator { get; set; }
        public Nullable<bool> GroupPolicyAdmin { get; set; }
        public Nullable<bool> PolicyAdmin { get; set; }
        public Nullable<bool> TeamManager { get; set; }
        public Nullable<bool> MeritApprove { get; set; }
        public Nullable<bool> LeaveApprove { get; set; }
        public Nullable<bool> OTApprove { get; set; }
        public Nullable<bool> TravelApprove { get; set; }
        public Nullable<bool> ClaimsApprove { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
