//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialLicence
    {
        public int SerialLicenceID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> Type { get; set; }
        public string ItemDesc { get; set; }
        public string Notes { get; set; }
        public string LicSer { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> RefDocID { get; set; }
        public Nullable<bool> Disposed { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public Nullable<int> DocumentID { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
