//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillsMatrix
    {
        public int SkillsMatrixID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> SkillSetID { get; set; }
        public Nullable<int> Proficiency { get; set; }
    
        public virtual SkillSet SkillSet { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
