//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemNotice
    {
        public int SystemNoticeID { get; set; }
        public Nullable<int> LinkType { get; set; }
        public Nullable<int> LinkID { get; set; }
        public Nullable<int> NoticeType { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> RSVP { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> MailedDate { get; set; }
        public Nullable<System.DateTime> ViewDate { get; set; }
        public Nullable<System.DateTime> ClearedDate { get; set; }
        public string Notice { get; set; }
    }
}
