//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teams()
        {
            this.TeamMembers = new HashSet<TeamMembers>();
        }
    
        public int TeamID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string TeamName { get; set; }
        public string TeamDescription { get; set; }
        public Nullable<int> TeamColour { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMembers> TeamMembers { get; set; }
    }
}
