//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelLog
    {
        public int TravelLogID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Status { get; set; }
        public string TravelAllowanceCurrency { get; set; }
        public Nullable<decimal> ConversionRate { get; set; }
        public Nullable<decimal> TravelAllowanceDailyAmt { get; set; }
        public Nullable<decimal> LocalCurrencyDailyValue { get; set; }
        public string PayCurrency { get; set; }
        public Nullable<int> ConvertedToClaimID { get; set; }
    
        public virtual Claims Claims { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
