//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehichles
    {
        public int VehicleID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Description { get; set; }
        public string RegNo { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> StartingKm { get; set; }
        public Nullable<bool> Disposed { get; set; }
        public Nullable<int> DisposalKm { get; set; }
    }
}
